id = "modelica"
name = "Modelica"
version = "0.0.1"
schema_version = 1
authors = ["Antoine Gautier <agautier@solamen.fr>"]
description = "Modelica language support"
repository = "https://github.com/AntoineGautier/zed-modelica"

[grammars.modelica]
repository = "https://github.com/OpenModelica/tree-sitter-modelica"
rev = "ee57ebfeedc515933d1dc4d41a5bc6af2f092afa"

[language_servers.modelica-language-server]
name = "Modelica Language Server"
languages = ["Modelica"]
