id = "modelica"
name = "Modelica"
version = "0.0.1"
schema_version = 1
authors = ["Antoine Gautier <agautier@solamen.fr>"]
description = "Modelica language support"
repository = "https://github.com/AntoineGautier/zed-modelica"

[grammars.modelica]
repository = "https://github.com/OpenModelica/tree-sitter-modelica"
rev = "96eebbdcc6a2a05c0d5769a2c4cf23eb84ac7bed"

[language_servers.modelica-language-server]
name = "Modelica Language Server"
languages = ["Modelica"]
